chore: add obs
linuxdeepin/dde-permission-manager pull request #3
Opened 2023-04-24 10:09 UTC by chenchongbiao

添加obs

2023-04-25 09:10 UTC, tsic404 commented
reuse 要先修一下吧

2023-04-26 00:47 UTC, chenchongbiao commented
> reuse 要先修一下吧

在修

2023-04-26 05:03 UTC, chenchongbiao commented
/review @tsic404

2023-04-26 05:08 UTC, tsic404 requested changes

2023-04-26 05:08 UTC, tsic404 commented on .obs/workflows.yml
> +              - x86_64
没有PKGBUILD可不用加archlinux

2023-04-26 05:22 UTC, chenchongbiao commented on .obs/workflows.yml
> +              - x86_64
行

2023-04-26 05:41 UTC, tsic404 approved these changes

2023-04-26 06:01 UTC, chenchongbiao commented
/merge

2023-04-26 06:01 UTC, merged