add missing path for dtkwidget.
linuxdeepin/dde-permission-manager pull request #5
Opened 2023-05-08 12:05 UTC by Gui-Yue

2023-05-08 12:08 UTC, Gui-Yue commented
I have read the CLA Document and I hereby sign the CLA.

2023-05-09 02:05 UTC, wineee requested changes

2023-05-09 02:05 UTC, wineee commented on debian/patches/add-missing-path.patch
> ++target_include_directories(dde-permission-manager PUBLIC
不要使用 patch 形式，直接改代码

不要使用硬编码，见：
https://github.com/linuxdeepin/dtkcore/blob/master/docs/MainPage.zh_CN.md

2023-05-09 05:04 UTC, Decodetalkers approved these changes

2023-05-09 05:05 UTC, BLumia commented
/merge

2023-05-09 05:06 UTC, wineee approved these changes
dtk 5.6 以后推荐用 Dtk::Widget，当然这个效果也一样

2023-05-09 05:06 UTC, merged